### ISSUE TITLE
Can you post the code as well I can contribute to this ?

### ISSUE THREAD

**Issue by shahabazshafizoomcar** [pkumar5/Tableau-Parcer#1]
Can you post the code as well I can contribute to this ?

**Comment by amrgpl** [comment]
Hi,
I don't develop anything :) I just use Your parser as I create dashboards
in Tableau and I find Your tool very useful in preparing documentation.
Thank You for that!

pt., 13 gru 2019, 08:02 użytkownik shahabazshafizoomcar <
notifications@github.com> napisał:

**Comment by pkumar5** [comment]
> Hi,
> I don't develop anything :) I just use Your parser as I create dashboards
> in Tableau and I find Your tool very useful in preparing documentation.
> Thank You for that!
> 
> pt., 13 gru 2019, 08:02 użytkownik shahabazshafizoomcar <
> notifications@github.com> napisał:
> …

amrgpl,
you are welcome...and I appretiate your feedback

**Comment by pkumar5** [comment]
> Can you post the code as well I can contribute to this ?

What are you planning on doing?

**Comment by shahabazshafizoomcar** [comment]
There are couple of features like data source attribution missing for each
calculation. Can create a chart to show the calculation flow. Many more
features like this.

**Comment by pkumar5** [comment]
Code added

**Comment by amrgpl** [comment]
Actually the datasource on each field is something that would be useful!

The chart to show the calculation flow seems difficult, isn't it?

pon., 16 gru 2019, 02:51 użytkownik shahabazshafizoomcar <
notifications@github.com> napisał:

> There are couple of features like data source attribution missing for each
> calculation. Can create a chart to show the calculation flow. Many more
> features like this.
>
>

**Comment by shahabazshafizoomcar** [comment]
Agreed ! In case of data binding how do we handle it?

**Comment by pkumar5** [comment]
what do you mean by data binding? 
the code has a section that deals with data sources...im not sure I understand the question
